# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samplemodel',
            name='apiGroup',
        ),
    ]
